server.port=${PORT:8084}
spring.application.name=ms-pedidos360-audit
spring.security.oauth2.resourceserver.jwt.issuer-uri=${ENTRA_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${ENTRA_AUDIENCE}
app.cors-origins=${CORS_ORIGINS:http://localhost:5173}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.health.rabbit.enabled=false
springdoc.api-docs.enabled=${OPENAPI_ENABLED:true}
springdoc.swagger-ui.enabled=${OPENAPI_ENABLED:true}
spring.rabbitmq.addresses=${RABBIT_ADDRESSES:localhost:5672}
spring.rabbitmq.username=${RABBIT_USER:pedidos360}
spring.rabbitmq.password=${RABBIT_PASSWORD}
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.listener.simple.acknowledge-mode=manual
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.delivery.timeout.ms=15000
spring.kafka.producer.properties.request.timeout.ms=5000
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record
app.catalog-url=${CATALOG_URL:http://localhost:8082}
app.orders-url=${ORDERS_URL:http://localhost:8083}
app.audit-url=${AUDIT_URL:http://localhost:8084}
app.report-url=${REPORT_URL:http://localhost:8085}
app.rabbit-admin-url=${RABBIT_ADMIN_URL:http://localhost:8087}
app.kafka-admin-url=${KAFKA_ADMIN_URL:http://localhost:8088}
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/app;MODE=Oracle;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=${DB_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.datasource.hikari.maximum-pool-size=5
