{
  "services": {
    "notify": {
      "image": "${IMAGE_REPOSITORY:?set repository}/notify:${IMAGE_TAG:-1.0.0}",
      "restart": "unless-stopped",
      "env_file": [
        ".env"
      ],
      "ports": [
        "8086:8086"
      ],
      "volumes": [
        "notify-data:/app/data"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
    }
  },
  "volumes": {
    "notify-data": {}
  }
}
