server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ENTRA_ISSUER_URI}
          audiences:
            - ${ENTRA_API_CLIENT_ID}

microservices:
  clientes:
    base-url: ${MS_CLIENTES_BASE_URL:http://localhost:8081}
